services:
  backend:
    image: rawandlaouini/arabic-transcription-backend:latest
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET=a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0
      - GOOGLE_CLIENT_ID=201334161885-7qktheuftruukg492deg3ugl2m0u0g61.apps.googleusercontent.com
      - FRONTEND_URL=http://localhost:3000
      - BASE_URL=http://localhost:8000
      - NGROK_URL=https://206d-34-143-253-186.ngrok-free.app/transcribe
      - NODE_ENV=development
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/downloads:/app/downloads
    networks:
      - app-network

  frontend:
    image: rawandlaouini/arabic-transcription-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
